Add missing `osaka-time` lcli param (#7183)
Getting this when running lcli with `--osaka-time`:

```
error: unexpected argument '--osaka-time' found

tip: a similar argument exists: '--shanghai-time'
```

This PR adds the missing `--osaka-time` option to `lcli`.